<a href="https://colab.research.google.com/github/aashi-singh-web/ML-LAB-CS/blob/main/ML_LAB5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np


df = pd.read_csv("/content/Iris.csv")
print(df.head())


   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa


In [ ]:
import pandas as pd
import numpy as np

# from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

from sklearn.linear_model import LinearRegression, LogisticRegression
from sklearn.metrics import (
    mean_squared_error,
    mean_absolute_error,
    r2_score,
    accuracy_score,
    confusion_matrix,
    classification_report
)

In [ ]:
# Load IRIS Dataset
# Column names as per UCI IRIS dataset
columns = [
    "sepal_length",
    "sepal_width",
    "petal_length",
    "petal_width",
    "species"
]

# Load data (no header in iris.data)
df = pd.read_csv('/content/Iris.csv', header=None, names=columns)

In [ ]:
print(df.head())


     sepal_length   sepal_width   petal_length   petal_width      species
Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
1             5.1           3.5            1.4           0.2  Iris-setosa
2             4.9           3.0            1.4           0.2  Iris-setosa
3             4.7           3.2            1.3           0.2  Iris-setosa
4             4.6           3.1            1.5           0.2  Iris-setosa


In [ ]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
Index: 151 entries, Id to 150
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   sepal_length  151 non-null    object
 1   sepal_width   151 non-null    object
 2   petal_length  151 non-null    object
 3   petal_width   151 non-null    object
 4   species       151 non-null    object
dtypes: object(5)
memory usage: 7.1+ KB
None


In [ ]:
df["species"] = df["species"].replace({
    "Iris-setosa": 0,
    "Iris-versicolor": 1,
    "Iris-virginica": 2
})

In [ ]:
df.head()

sepal_length   sepal_width   petal_length   petal_width  species
Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
1             5.1           3.5            1.4           0.2        0
2             4.9           3.0            1.4           0.2        0
3             4.7           3.2            1.3           0.2        0
4             4.6           3.1            1.5           0.2        0

In [ ]:
X_lr = df[["sepal_length", "sepal_width", "petal_width"]]
y_lr = df["petal_length"]

In [ ]:
X_train_lr, X_test_lr, y_train_lr, y_test_lr = train_test_split(
    X_lr, y_lr, test_size=0.2, random_state=42)

In [ ]:
# Train Linear Regression Model
lr_model = LinearRegression()

In [ ]:
lr_model.fit(X_train_lr, y_train_lr)

LinearRegression()

In [ ]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
Index: 151 entries, Id to 150
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   sepal_length  151 non-null    object
 1   sepal_width   151 non-null    object
 2   petal_length  151 non-null    object
 3   petal_width   151 non-null    object
 4   species       151 non-null    object
dtypes: object(5)
memory usage: 11.1+ KB
None


First, let's confirm the `df` is correctly loaded and processed after the previous fix to cell `e8Jp4QBytbg_`. We will display the head and info of the DataFrame.

In [ ]:
import pandas as pd


df = pd.read_csv('/content/Iris.csv')


if 'Id' in df.columns:
    df.drop(columns=['Id'], inplace=True)

df.rename(columns={
    "SepalLengthCm": "sepal_length",
    "SepalWidthCm": "sepal_width",
    "PetalLengthCm": "petal_length",
    "PetalWidthCm": "petal_width",
    "Species": "species"
}, inplace=True)


for col in ["sepal_length", "sepal_width", "petal_length", "petal_width"]:
    df[col] = pd.to_numeric(df[col], errors='coerce')


df.dropna(inplace=True)

print('DataFrame head after correction:')
print(df.head())
print('\nDataFrame info after correction:')
print(df.info())

DataFrame head after correction:
   sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

DataFrame info after correction:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB
None


Now that `df` has been properly loaded and its columns are numeric, we can proceed with replacing species names with numerical values and then redefine the features (`X_lr`) and target (`y_lr`).

In [ ]:
df["species"] = df["species"].replace({
    "Iris-setosa": 0,
    "Iris-versicolor": 1,
    "Iris-virginica": 2
})

print('DataFrame head after species encoding:')
print(df.head())

DataFrame head after species encoding:
   sepal_length  sepal_width  petal_length  petal_width  species
0           5.1          3.5           1.4          0.2        0
1           4.9          3.0           1.4          0.2        0
2           4.7          3.2           1.3          0.2        0
3           4.6          3.1           1.5          0.2        0
4           5.0          3.6           1.4          0.2        0


/tmp/ipython-input-1239912902.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df["species"] = df["species"].replace({


In [ ]:
X_lr = df[["sepal_length", "sepal_width", "petal_width"]]
y_lr = df["petal_length"]

print('\nX_lr head:')
print(X_lr.head())
print('\ny_lr head:')
print(y_lr.head())


X_lr head:
   sepal_length  sepal_width  petal_width
0           5.1          3.5          0.2
1           4.9          3.0          0.2
2           4.7          3.2          0.2
3           4.6          3.1          0.2
4           5.0          3.6          0.2

y_lr head:
0    1.4
1    1.4
2    1.3
3    1.5
4    1.4
Name: petal_length, dtype: float64


Next, we'll split the data into training and testing sets, re-initialize the Linear Regression model, and then train it. This time, the training should succeed without the `ValueError`.

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

X_train_lr, X_test_lr, y_train_lr, y_test_lr = train_test_split(
    X_lr, y_lr, test_size=0.2, random_state=42)

lr_model = LinearRegression()
lr_model.fit(X_train_lr, y_train_lr)

print('Linear Regression model trained successfully!')
print(f'Model coefficients: {lr_model.coef_}')
print(f'Model intercept: {lr_model.intercept_}')

Linear Regression model trained successfully!
Model coefficients: [ 0.72417306 -0.641963    1.46632204]
Model intercept: -0.2504659324864602


In [ ]:
# Predictions
y_pred_lr = lr_model.predict(X_test_lr)

In [ ]:
# Evaluate Linear Regression Model
print("LINEAR REGRESSION EVALUATION")
print("Mean Squared Error:", mean_squared_error(y_test_lr, y_pred_lr))
print("Mean Absolute Error:", mean_absolute_error(y_test_lr, y_pred_lr))
print("R2 Score:", r2_score(y_test_lr, y_pred_lr))

LINEAR REGRESSION EVALUATION
Mean Squared Error: 0.12991981605759947
Mean Absolute Error: 0.2606173239288886
R2 Score: 0.9603587427485161


In [ ]:
# Load data (no header in iris.data)
df = pd.read_csv(r'/content/Iris.csv')

In [ ]:
# Encode Categorical Target (Species)
df["Species"] = df["Species"].replace({
    "Iris-setosa": 0,
    "Iris-versicolor": 1,
    "Iris-virginica": 2
})

/tmp/ipython-input-649592999.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df["Species"] = df["Species"].replace({


In [ ]:
X_lr = df[["SepalLengthCm", "SepalWidthCm", "PetalWidthCm"]]
y_lr = df["PetalLengthCm"]

In [ ]:
lr_model = LinearRegression()
lr_model.fit(X_train_lr, y_train_lr)

LinearRegression()

In [ ]:
y_pred_lr = lr_model.predict(X_test_lr)

In [ ]:
# For LOGISTIC REGRESSION (Classification – Predicting Iris Species)

# Prepare Data for Logistic Regression
X = df.drop(columns=["Species"])
y = df["Species"]



In [ ]:
# Train–Test Split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)


In [ ]:
# Feature Scaling
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)



In [ ]:
# Train Logistic Regression Model
log_model = LogisticRegression(max_iter=200)
log_model.fit(X_train, y_train)


LogisticRegression(max_iter=200)

In [ ]:

# Predictions
y_pred_log = log_model.predict(X_test)


In [ ]:

#  Evaluate Logistic Regression Model
print("\nLOGISTIC REGRESSION EVALUATION")
print("Accuracy:", accuracy_score(y_test, y_pred_log))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred_log))
print("\nClassification Report:\n", classification_report(y_test, y_pred_log))


LOGISTIC REGRESSION EVALUATION
Accuracy: 1.0

Confusion Matrix:
 [[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]

Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30



In [ ]:
# Prepare Data for Logistic Regression
X = df.drop("Species", axis=1)
y = df["Species"]