<a href="https://colab.research.google.com/github/aashi-singh-web/ML-LAB-CS/blob/main/ML_Lab1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(arr.shape)
print(arr.dtype)

[1 2 3 4 5]
(5,)
int64


In [ ]:
import numpy as np

zeros_matrix = np.zeros((3, 4))
ones_matrix = np.ones((2, 5))

print(zeros_matrix)
print(zeros_matrix.shape)

print(ones_matrix)
print(ones_matrix.shape)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
(3, 4)
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
(2, 5)


In [ ]:
import numpy as np

arr = np.arange(1, 13)
reshaped_arr = arr.reshape(3, 4)

print(arr)
print(arr.shape)

print(reshaped_arr)
print(reshaped_arr.shape)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
(12,)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)


In [ ]:
import numpy as np

arr = np.random.randint(1, 100, 10)

print(arr)
print(np.min(arr))
print(np.max(arr))
print(np.mean(arr))
print(np.sum(arr))

[54 57 86 35 52 15  6 80 61 98]
6
98
54.4
544


In [ ]:
import pandas as pd

data = {
    "Name": ["Amit", "Neha", "Ravi", "Sneha"],
    "Marks": [85, 92, 78, 88]
}

df = pd.DataFrame(data)
print(df)
print(df.dtypes)

    Name  Marks
0   Amit     85
1   Neha     92
2   Ravi     78
3  Sneha     88
Name     object
Marks     int64
dtype: object


In [ ]:
import pandas as pd
from google.colab import files
uploaded = files.upload()
df = pd.read_csv("BostonHousing.csv")
print(df.head())
print(df.tail())

Saving BostonHousing.csv to BostonHousing.csv
      crim    zn  indus  chas    nox     rm   age     dis  rad  tax  ptratio  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296     15.3   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242     17.8   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242     17.8   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222     18.7   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222     18.7   

        b  lstat  medv  
0  396.90   4.98  24.0  
1  396.90   9.14  21.6  
2  392.83   4.03  34.7  
3  394.63   2.94  33.4  
4  396.90   5.33  36.2  
        crim   zn  indus  chas    nox     rm   age     dis  rad  tax  ptratio  \
501  0.06263  0.0  11.93     0  0.573  6.593  69.1  2.4786    1  273     21.0   
502  0.04527  0.0  11.93     0  0.573  6.120  76.7  2.2875    1  273     21.0   
503  0.06076  0.0  11.93     0  0.573  6.976  91.0  2.1675    1  273     21.0   

In [ ]:
import pandas as pd

df = pd.read_csv("BostonHousing.csv")

print(df.info())
print(df.shape)
print(df.isnull().sum())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 14 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   crim     506 non-null    float64
 1   zn       506 non-null    float64
 2   indus    506 non-null    float64
 3   chas     506 non-null    int64  
 4   nox      506 non-null    float64
 5   rm       506 non-null    float64
 6   age      506 non-null    float64
 7   dis      506 non-null    float64
 8   rad      506 non-null    int64  
 9   tax      506 non-null    int64  
 10  ptratio  506 non-null    float64
 11  b        506 non-null    float64
 12  lstat    506 non-null    float64
 13  medv     506 non-null    float64
dtypes: float64(11), int64(3)
memory usage: 55.5 KB
None
(506, 14)
crim       0
zn         0
indus      0
chas       0
nox        0
rm         0
age        0
dis        0
rad        0
tax        0
ptratio    0
b          0
lstat      0
medv       0
dtype: int64


In [ ]:
import pandas as pd

df = pd.read_csv("BostonHousing.csv")

print(df.describe())

             crim          zn       indus        chas         nox          rm  \
count  506.000000  506.000000  506.000000  506.000000  506.000000  506.000000   
mean     3.613524   11.363636   11.136779    0.069170    0.554695    6.284634   
std      8.601545   23.322453    6.860353    0.253994    0.115878    0.702617   
min      0.006320    0.000000    0.460000    0.000000    0.385000    3.561000   
25%      0.082045    0.000000    5.190000    0.000000    0.449000    5.885500   
50%      0.256510    0.000000    9.690000    0.000000    0.538000    6.208500   
75%      3.677083   12.500000   18.100000    0.000000    0.624000    6.623500   
max     88.976200  100.000000   27.740000    1.000000    0.871000    8.780000   

              age         dis         rad         tax     ptratio           b  \
count  506.000000  506.000000  506.000000  506.000000  506.000000  506.000000   
mean    68.574901    3.795043    9.549407  408.237154   18.455534  356.674032   
std     28.148861    2.1057

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive
